<?php

/**
 * This file is part of the froxlor project.
 * Copyright (c) 2010 the froxlor Team (see authors).
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you can also view it online at
 * https://files.froxlor.org/misc/COPYING.txt
 *
 * @copyright  the authors
 * @author     froxlor team <team@froxlor.org>
 * @license    https://files.froxlor.org/misc/COPYING.txt GPLv2
 */

namespace Froxlor\WebAuthn;

use Exception;
use Froxlor\Settings;
use Froxlor\UI\Panel\UI;
use lbuchs\WebAuthn\WebAuthn;

/**
 * Froxlor wrapper around lbuchs/webauthn for FIDO2/Passkey support.
 *
 * Handles credential registration and assertion verification for WebAuthn
 * (type_2fa = 3). Each user may register multiple credentials (e.g. several
 * hardware keys). Credentials are persisted in panel_webauthn_credentials.
 *
 * Registration flow
 * -----------------
 *  1. getCreateArgs()   → JSON options delivered to the browser
 *  2. Browser calls navigator.credentials.create()
 *  3. processCreate()   → verify & return credential data for storage
 *
 * Authentication flow
 * -------------------
 *  1. getGetArgs()      → JSON assertion options delivered to the browser
 *  2. Browser calls navigator.credentials.get()
 *  3. processGet()      → verify assertion, return updated sign-count
 */
class FroxlorWebAuthn
{
	private WebAuthn $webAuthn;

	/**
	 * @throws Exception
	 */
	public function __construct()
	{
		$hostname = Settings::Get('system.hostname') ?: ($_SERVER['HTTP_HOST'] ?? 'localhost');
		// RP ID must be a registrable domain suffix (no port)
		$rpId = preg_replace('/:\d+$/', '', $hostname);

		// Build the allowed origin from the current request
		$scheme = UI::requestIsHttps() ? 'https' : 'http';
		$host = $_SERVER['HTTP_HOST'] ?? $hostname;
		$origin = $scheme . '://' . $host;

		$this->webAuthn = new WebAuthn('Froxlor', $rpId, [$origin]);
	}

	/**
	 * Return the PublicKeyCredentialCreationOptions for navigator.credentials.create().
	 *
	 * @param int    $userId              Numeric user ID (admin or customer)
	 * @param string $userName            Login name
	 * @param string $userDisplayName     Human-readable name
	 * @param array  $excludeCredentials  base64-encoded credential IDs to exclude
	 *
	 * @return \stdClass  Directly JSON-serialisable options object
	 * @throws Exception
	 */
	public function getCreateArgs(int $userId, string $userName, string $userDisplayName, array $excludeCredentials = []): \stdClass
	{
		// Convert stored base64 credential IDs back to raw binary for the exclude list
		$excludeIds = array_map(
			fn($id) => base64_decode($id),
			$excludeCredentials
		);

		return $this->webAuthn->getCreateArgs(
			// User ID as 4-byte big-endian binary (covers int(11) range in MySQL, max ~2.1 billion)
			pack('N', $userId),
			$userName,
			$userDisplayName,
			30,                   // timeout in seconds
			false,                // requireResidentKey
			false,                // requireUserVerification
			empty($excludeIds) ? null : $excludeIds
		);
	}

	/**
	 * Return the PublicKeyCredentialRequestOptions for navigator.credentials.get().
	 *
	 * @param array $credentialIds  base64-encoded credential IDs registered for this user
	 *
	 * @return \stdClass  Directly JSON-serialisable options object
	 * @throws Exception
	 */
	public function getGetArgs(array $credentialIds): \stdClass
	{
		$binaryIds = array_map(
			fn($id) => base64_decode($id),
			$credentialIds
		);

		return $this->webAuthn->getGetArgs(
			$binaryIds,
			30,    // timeout
			true,  // allowUsb
			true,  // allowNfc
			false, // allowBle
			true,  // allowHybrid (passkeys)
			false  // requireUserVerification
		);
	}

	/**
	 * Return the base64-encoded binary challenge that was generated by the most
	 * recent getCreateArgs() or getGetArgs() call (for session storage).
	 *
	 * @return string
	 */
	public function getChallenge(): string
	{
		return base64_encode($this->webAuthn->getChallenge()->getBinaryString());
	}

	/**
	 * Verify the attestation response from navigator.credentials.create().
	 *
	 * @param string $clientDataJSON     Raw value from the browser (NOT base64-decoded)
	 * @param string $attestationObject  Raw value from the browser (NOT base64-decoded)
	 * @param string $challenge          base64-encoded challenge (from session)
	 *
	 * @return \stdClass  Object with credentialId, publicKey, signCount fields
	 * @throws Exception  on verification failure
	 */
	public function processCreate(string $clientDataJSON, string $attestationObject, string $challenge): \stdClass
	{
		$challengeBuffer = \lbuchs\WebAuthn\Binary\ByteBuffer::fromBase64Url(
			rtrim(strtr(base64_encode(base64_decode($challenge)), '+/', '-_'), '=')
		);

		$data = $this->webAuthn->processCreate(
			$clientDataJSON,
			$attestationObject,
			$challengeBuffer,
			false, // requireUserVerification
			true,  // failIfRootMismatch
			false  // requireResidentKey
		);

		return (object)[
			'credentialId' => base64_encode($data->credentialId->getBinaryString()),
			'publicKey'    => base64_encode($data->credentialPublicKey->getBinaryString()),
			'signCount'    => (int)$data->signCount,
		];
	}

	/**
	 * Verify the assertion response from navigator.credentials.get().
	 *
	 * @param string $clientDataJSON     Raw value from the browser
	 * @param string $authenticatorData  Raw value from the browser
	 * @param string $signature          Raw value from the browser
	 * @param string $userHandle         Raw value from the browser (may be empty)
	 * @param string $publicKey          base64-encoded stored public key
	 * @param string $challenge          base64-encoded challenge (from session)
	 * @param int    $prevSignCount      Sign-count from the stored credential
	 *
	 * @return int  Updated sign-count (persist this after successful verification)
	 * @throws Exception  on verification failure
	 */
	public function processGet(
		string $clientDataJSON,
		string $authenticatorData,
		string $signature,
		string $userHandle,
		string $publicKey,
		string $challenge,
		int $prevSignCount
	): int {
		$challengeBuffer = \lbuchs\WebAuthn\Binary\ByteBuffer::fromBase64Url(
			rtrim(strtr(base64_encode(base64_decode($challenge)), '+/', '-_'), '=')
		);

		$publicKeyBuffer = new \lbuchs\WebAuthn\Binary\ByteBuffer(base64_decode($publicKey));

		$this->webAuthn->processGet(
			$clientDataJSON,
			$authenticatorData,
			$signature,
			$userHandle ?: null,
			$publicKeyBuffer,
			$challengeBuffer,
			$prevSignCount,
			false  // requireUserVerification
		);

		// Extract updated sign-count from authenticatorData:
		// Bytes  0-31: RP ID hash (32 bytes)
		// Byte     32: flags (1 byte)
		// Bytes 33-36: signature counter, big-endian uint32 (4 bytes)
		$authDataBin = base64_decode($authenticatorData);
		if (strlen($authDataBin) >= 37) {
			$newCount = unpack('N', substr($authDataBin, 33, 4))[1];
		} else {
			$newCount = $prevSignCount;
		}

		return $newCount;
	}
}
